DAT-1989: Replace clone from Github with docker container

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -17,12 +17,16 @@ echo "Running pre-commit hook on branch ${branch_name}: "
 echo "SAST scan..."
 
 for file in $(git diff-index --name-only --diff-filter=ACMT --cached HEAD -- ); do
-  /opt/sast-scan.sh --type python --type typescript --target "$file" || exit_code=1
+  docker run -v "$(pwd)":/tmp "eu.gcr.io/vwt-d-gew1-dat-cloudbuilders/cloudbuilder-sast" --type python --type typescript --target /tmp/"$file" || exit_code=1
 done
-
+if [[ "$exit_code" -eq 1 ]]; then
+  echo -e "\e[1;31mError: Docker run wasn't executed with sufficient permissions."\
+          "See this page: https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user"\
+          "for instructions on managing Docker as a non-root user.🔗 '\e[0m"
+fi
 if [ "$exit_code" != 0 ] ; then
-        echo
-        echo "ERROR: SAST scan failed. Your changes were not committed."
-        echo "in $git_dir/$file:"
-        exit 1
+  echo
+  echo "ERROR: SAST scan failed. Your changes were not committed."
+  echo "in $git_dir/$file:"
+  exit 1
 fi
