DAT-2576: Run SAST only on staged files preserving paths, include config

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -17,6 +17,12 @@ echo "Running pre-commit hook on branch ${branch_name}: "
 ##############################################################################
 echo "SAST scan..."
 
+if ! docker run hello-world > /dev/null 2>&1; then
+  echo -e "\e[1;31mError: Docker run wasn't executed with sufficient permissions."\
+          "See this page: https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user"\
+          "for instructions on managing Docker as a non-root user.🔗 '\e[0m"
+fi
+
 if [[ $hook_branch == "develop" ]]; then
   echo -e "\e[33mWARNING: you are running a development version of the git hooks! Use the master branch for more" \
    "stable and secure hooks\e[0m"
@@ -24,14 +30,20 @@ if [[ $hook_branch == "develop" ]]; then
 else
   docker_image="eu.gcr.io/vwt-p-gew1-dat-cloudbuilders/cloudbuilder-sast"
 fi
+mkdir tmp-pre-commit-folder > /dev/null 2>&1
 
-docker run --volume "$git_dir":/tmp $docker_image --target /tmp --context pre-commit || exit_code=1
-
-if ! docker run hello-world > /dev/null 2>&1; then
-  echo -e "\e[1;31mError: Docker run wasn't executed with sufficient permissions."\
-          "See this page: https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user"\
-          "for instructions on managing Docker as a non-root user.🔗 '\e[0m"
+for file in $(git diff-index --name-only --diff-filter=ACMT --cached HEAD -- ); do
+  (cd tmp-pre-commit-folder && mkdir -p $file && cp ../$file $file)
+done
+[ -d "$git_dir"/node_modules ] && cp -r "$git_dir"/node_modules tmp-pre-commit-folder
+if [[ -d .sast-config ]]; then
+  cp -r .sast-config tmp-pre-commit-folder
 fi
+
+docker run --volume tmp-pre-commit-folder:/tmp $docker_image --target /tmp --context pre-commit || exit_code=1
+
+rm -rf tmp-pre-commit-folder
+
 if [ "$exit_code" != 0 ] ; then
   echo
   echo "ERROR: SAST scan failed. Your changes were not committed."
